### ----------------------------  GET ALL ----------------------------
GET HTTP://localhost:3000/api/roles


### ----------------------------  GET ONE ----------------------------

 
### ----------------------------  CREATE (POST) ----------------------------
POST http://localhost:3000/api/roles
Content-Type: application/json

{
    "descripcion": "invitado"
}

### ----------------------------  UPDATE (PUT) ----------------------------



### modificar un  character(put y patch)
###PUT: para modificaciones COMPLETAS (todos los atributos que puedan ser  modificados)

### ----------------------------  DELETE  ----------------------------

