version: '3.8'
services:
  db:
    image: percona/percona-server
    container_name: ps8-dsw-VolquetesHnos
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_PASSWORD: 'volqueteshermanos'
      MYSQL_USER: 'volqueteshermanos'
      MYSQL_DATABASE: 'sysvol'
    volumes:
      - volquetesBD:/var/lib/mysql
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - '3382:3382'

volumes:
  volquetesBD:
