### ----------------------------  GET ALL ----------------------------
GET HTTP://localhost:3000/api/users


### ----------------------------  GET ONE ----------------------------
GET HTTP://localhost:3000/api/users/4
 
### ----------------------------  CREATE (POST) ----------------------------
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "nombre_usuario":"Pablo",
//<<<<<<< HEAD
    "email": "pvirgolini@gmail.com",
//=======
//>>>>>>> 96e332406f01fe92b74e6e34ade107af8e31b13d
    "password":"12345",
    "rol": "1"
}

### ----------------------------  UPDATE (PUT) ----------------------------
### modificar un  character(put y patch)
###PUT: para modificaciones COMPLETAS (todos los atributos que puedan ser  modificados)
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
    "nombre_usuario":"Camilo",
    "email": "caamilopereyra01@gmail.com",
    "contraseña":"123456",
    "rol":"admin"
}

### ----------------------------  DELETE  ----------------------------

DELETE http://localhost:3000/api/users/1

### ----------------------------  GetAllRoles del usuario  ----------------------------
GET http://localhost:3000/api/users/getAllRoles
