### ----------------------------  GET ALL ----------------------------
GET HTTP://localhost:3000/api/tipovolquetes


### ----------------------------  GET ONE ----------------------------
GET HTTP://localhost:3000/api/tipovolquetes/4
 

### ----------------------------  CREATE (POST) ----------------------------
POST http://localhost:3000/api/tipovolquetes
Content-Type: application/json

{
    //"id_tipo_volquete":"4", no se define ya que es autoincremental
    "descripcion_tipo_volquete":"EXTRA CHICO"
}




### ----------------------------  UPDATE (PUT) ----------------------------



### modificar un  character(put y patch)
###PUT: para modificaciones COMPLETAS (todos los atributos que puedan ser  modificados)
PUT http://localhost:3000/api/tipovolquetes/4
Content-Type: application/json

{
   "descripcion_tipo_volquete":"Extra chico"
}




### ----------------------------  UPDATE (PATCH) ----------------------------

###PATCH: para modificaciones de un subconjunto de atributos.
PATCH http://localhost:3000/api/tipovolquetes/4
Content-Type: application/json

{
   "descripcion_tipo_volquete":"Extra - chico"
}




### ----------------------------  DELETE  ----------------------------

DELETE http://localhost:3000/api/tipovolquetes/4


